name: leland
description: Leland T&M Application

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  cached_network_image: ^2.0.0-rc
  connectivity: ^0.4.9+2
  flutter_statusbarcolor: ^0.2.3
  dio: ^3.0.10
  dio_http_cache: ^0.2.11
  progress_indicators: ^0.1.5
  toast: ^0.1.5
  dotted_border: ^1.0.7
  image_picker: ^0.6.7+20
  intl: ^0.17.0
  shared_preferences: ^2.0.5
  device_info: ^2.0.0
  dropdown_search: ^0.5.0
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: medium
      fonts:
        - asset: font/Poppins-Medium.ttf

    - family: regular
      fonts:
        - asset: font/Poppins-Regular.ttf



